/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gejiahui_androidpractice_blur_BlurByJni */

#ifndef _Included_com_gejiahui_androidpractice_blur_BlurByJni
#define _Included_com_gejiahui_androidpractice_blur_BlurByJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gejiahui_androidpractice_blur_BlurByJni
 * Method:    blurByJni
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_gejiahui_androidpractice_blur_BlurByJni_blurByJni
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
