/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gejiahui_androidpractice_jni_JniLibrary */

#ifndef _Included_com_gejiahui_androidpractice_jni_JniLibrary
#define _Included_com_gejiahui_androidpractice_jni_JniLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gejiahui_androidpractice_jni_JniLibrary
 * Method:    getTimByJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gejiahui_androidpractice_jni_JniLibrary_getTimByJni
  (JNIEnv *, jobject);

/*
 * Class:     com_gejiahui_androidpractice_jni_JniLibrary
 * Method:    getTimeStaticByJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gejiahui_androidpractice_jni_JniLibrary_getTimeStaticByJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
